# Artificial Neural Network

### Importing the libraries

In [2]:
pip install --upgrade tensorflow

Note: you may need to restart the kernel to use updated packages.  Downloading termcolor-1.1.0.tar.gz (3.9 kB)

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4847 sha256=8182af7417750f3eacdcc5f3daa38125858d72235d9d247553ee020d67883ff3
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor


In [3]:

import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5530 - accuracy: 0.7832
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4816 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 879us/step - loss: 0.4585 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 888us/step - loss: 0.4448 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4352 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4272 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 873us/step - loss: 0.4208 - accuracy: 0.7977
Epoch 8/100
250/250 [==============================] - 0s 879us/step - loss: 0.4156 - accuracy: 0.8004
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4099 - accuracy: 0.8163
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4038 

250/250 [==============================] - 0s 1ms/step - loss: 0.3424 - accuracy: 0.8593
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3421 - accuracy: 0.8608
Epoch 82/100
250/250 [==============================] - 0s 831us/step - loss: 0.3420 - accuracy: 0.8602
Epoch 83/100
250/250 [==============================] - 0s 968us/step - loss: 0.3418 - accuracy: 0.8606
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3419 - accuracy: 0.8618
Epoch 85/100
250/250 [==============================] - 0s 941us/step - loss: 0.3417 - accuracy: 0.8590
Epoch 86/100
250/250 [==============================] - 0s 818us/step - loss: 0.3418 - accuracy: 0.8591
Epoch 87/100
250/250 [==============================] - 0s 888us/step - loss: 0.3413 - accuracy: 0.8602
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3412 - accuracy: 0.8590
Epoch 89/100
250/250 [==============================] - 0s 982us/step - loss: 0.3415 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation



Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 82ms/step
[[False]]


### Predicting the Test set results

In [21]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 789us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1504   91]
 [ 194  211]]


0.8575